import Head from "next/head";
import ProductHome from "../components/ProductHome";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ruby Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductHome />
    </div>
  );
}
